// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEG2y_YT4jQrSHR3vkC6OuX-yyaJXwGMM',
    appId: '1:1053414525131:web:171f0a0247df0be316b34e',
    messagingSenderId: '1053414525131',
    projectId: 'status-shop-533d8',
    authDomain: 'status-shop-533d8.firebaseapp.com',
    storageBucket: 'status-shop-533d8.firebasestorage.app',
    measurementId: 'G-92NNT6P4XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZsIGGfXVv8hoTGis903dr_wDfuT_dP_o',
    appId: '1:1053414525131:android:28c5bbe8564b654516b34e',
    messagingSenderId: '1053414525131',
    projectId: 'status-shop-533d8',
    storageBucket: 'status-shop-533d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzGym1F48-9tffQOeiPdMD-SjdXkQ7G4k',
    appId: '1:1053414525131:ios:cbf1683d79ec1e5716b34e',
    messagingSenderId: '1053414525131',
    projectId: 'status-shop-533d8',
    storageBucket: 'status-shop-533d8.firebasestorage.app',
    iosBundleId: 'com.statusshop.statusShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzGym1F48-9tffQOeiPdMD-SjdXkQ7G4k',
    appId: '1:1053414525131:ios:cbf1683d79ec1e5716b34e',
    messagingSenderId: '1053414525131',
    projectId: 'status-shop-533d8',
    storageBucket: 'status-shop-533d8.firebasestorage.app',
    iosBundleId: 'com.statusshop.statusShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEG2y_YT4jQrSHR3vkC6OuX-yyaJXwGMM',
    appId: '1:1053414525131:web:6930b5f573d153cd16b34e',
    messagingSenderId: '1053414525131',
    projectId: 'status-shop-533d8',
    authDomain: 'status-shop-533d8.firebaseapp.com',
    storageBucket: 'status-shop-533d8.firebasestorage.app',
    measurementId: 'G-DH0XC30B1D',
  );

}